language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t etiennewl/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true etiennewl/react-test npm test -- --coverage

after_success:
    - docker build -t etiennewl/multi-client ./client
    - docker build -t etiennewl/multi-nginx ./nginx
    - docker build -t etiennewl/multi-server ./server
    - docker build -t etiennewl/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker hub
    - docker push etiennewl/multi-client
    - docker push etiennewl/multi-nginx
    - docker push etiennewl/multi-server
    - docker push etiennewl/multi-worker
deploy:
    provider: elasticbeanstalk
    region: eu-west-3
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-3-831850936933
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    #edge: true
    #provider: elasticbeanstalk