language: generic
sudo: required
services:
    -docker
before_install:
    - docker build -t etiennewl/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true etiennewl/react-test npm test -- --coverage

after_success:
    - docker build -t etiennewl/multi-client ./client
    - docker build -t etiennewl/multi-nginx ./nginx
    - docker build -t etiennewl/multi-server ./server
    - docker build -t etiennewl/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker hub
    - docker push etiennewl/multi-client
    - docker push etiennewl/multi-nginx
    - docker push etiennewl/multi-server
    - docker push etiennewl/multi-worker
